public enum tokenType {
    ENDOFLINE, NUMBER, IDENTIFIER, PUNCTUATION, DEFINE, VAR, IF, THEN, ELSE, ELSIF, WHILE, REPEAT, UNTIL, FOR, FROM, TO, VARIABLES, CONSTANTS, WRITE, INTEGER, REAL, CHARACTER, CHARACTERLITERAL, STRING, 
    STRINGLITERAL, BOOLEAN, BOOLEANLITERAL, PLUS, MINUS, MULTIPLY, DIVIDE, MODULO, EQUAL, ASSIGN, LESS, GREATER, LESSEQUAL, GREATEREQUAL, NOTEQUAL, LEFTPAREN, RIGHTPAREN, LEFTBRACE, RIGHTBRACE, DECLARATION, 
    COMMA, QUOTE, UNKNOWN, INDENT, DEDENT
}
